Desktop/Django/conbrio2/app/urls.py
from django.urls import path
from . import views
from .views import index , signup
from django.contrib.auth import views as auth_views

app_name='app'
urlpatterns = [
    path('',index.as_view(), name='index'),
    path('signup/',views.signup, name='signup'),
    path('login/',
    auth_views.LoginView.as_view(template_name='app/login.html'),
    name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),

]

Desktop/Django/conbrio2/conbrio2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),

]

Desktop/Django/conbrio2/app/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title=models.CharField(max_length=100)
    primaryCategory=models.BooleanField(default=False)
     
    def __str__(self):
        return self.title


class Product(models.Model):
    mainimage=models.ImageField(upload_to='photos/',blank=True)
    name=models.CharField(max_length=100)
    slug=models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    
    def __str__(self):
        return self.name

Desktop/Django/conbrio2/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class signupForm(UserCreationForm):
    email=forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model=User
        fields=('username','email','password')

Desktop/Django/conbrio2/app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm 
from .forms import signupForm
from django.views.generic import ListView
from app.models import Product,Category
# Create your views here.


class index(ListView):
    model=Product
    templates_name='app/product_list.html'


def signup(request):
    if request.method=='POST':
        form=signupForm(request.POST)
        if form.is_valid():
            user=form.save()
            auth_login(request,user)
            return redirect('index')
    else:
            form=signupForm()
    return render(request,'app/signup.html',{'form':form})

Desktop/Django/conbrio2/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja-JP">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Great+Vibes|Kaushan+Script|Permanent+Marker&display=swap" rel="stylesheet">

<title>Title</title>
</head>
<body>

  <div class="container-header">
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4">
          <a href="{% url 'app:index' %}"><h1>Conbrio</h1></a>
        </div>

        <div class="col-sm-1 col-md-2 col-lg-2" ></div>

    <div class="col-sm-6 col-md-4 col-lg-4" style="padding-top: 10px;" >
       <i class="fab fa-twitter"></i>
       <i class="fab fa-facebook-square"></i>
       <i class="fab fa-instagram"></i>
      </div>

      {% if request.user.is_authenticated %}  
        <h5 class="nav-item dropdown" style="margin-top: -20px; color:rgb(167, 133, 110);">
            <a  href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle" style="font-size: 50px; padding-left: 50px;"></i>
              </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="color:rgb(167, 133, 110);">
              <a class="dropdown-item" href="#">投稿</a>
              <a class="dropdown-item" href="{% url 'app:logout'  %}">Logout</a>
            </div>
          </h5>

      {% else %}
        <h5 class="nav-item">
            <a href="{% url 'app:login' %}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 70px;">login</a>
            <a href="{% url 'app:signup' %}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 70px;">signup</a>
       </h5>
      {% endif %}
        </div>
    </div>
  </div>
</div>
</div>

{% block content %}
{% endblock %}


<a href="/"><h6>Conbrio</h6></a>




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/css" src="{%static 'js/style.js'%}"></script>

</body>
</html>

Desktop/Django/conbrio2/app/templates/app/login.html
{% extends "app/base.html" %}

{% block title %}

login


  
{% endblock %}

{% block content %}

<h2>login</h2>
<form method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">login</button>
</form>

{% endblock %}

Desktop/Django/conbrio2/app/templates/app/signup.html
{% extends "app/base.html" %}

{% block content %}

<div class="container-login">
    <div class="row">
            <div class="col-sm-6 col-md-12 col-lg-12">

<h3>ユーザー登録</h3>
<form method="POST" action="{%url 'app:signup'%}" style=" color: rgb(167, 133, 110); ">{% csrf_token %}
    <label>meiladdress</label>
    {{form.email}}
    {{form.email.errors}}
    <br>
    <label>password</label>
    {{form.password1}}
    {{form.password1.errors}}
    <br>
    <label>password(確認用)</label>
    {{form.password2}}
    {{form.password2.errors}}
    <br>
    <input style=" color: rgb(167, 133, 110);" type="submit" value="登録する">
    

</form>
  
{% endblock %}