Desktop/Django/conbrio11/app/urls.py
from django.urls import path
from .views import Index
from . import views
from django.contrib.auth import views as auth_views

app_name='mainapp'

urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('users/<int:pk>/',views.users_detail,name='users_detail'),
    path('plans/new/',views.plans_new,name='plans_new'),
    path('plan/<str:category>/',views.plans_category,name='plans_category'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='app/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

Desktop/Django/conbrio11/conbrio6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls',namespace='mainapp')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desktop/Django/conbrio11/app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=20)

    def __str__(self):
        return self.title

    

class Plan(models.Model):
    mainimage=models.ImageField(upload_to='photos/',blank=True)
    title=models.CharField(max_length=100)
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    category=models.ForeignKey(Category,on_delete=models.PROTECT,default=1)
    created_at = models.DateTimeField(auto_now=True)
    meeting_place = models.CharField(max_length=200)
    moving_method = models.CharField(max_length=200)
    second_place = models.CharField(max_length=200)
    third_place = models.CharField(max_length=200)


    def __str__(self):
        return self.title

Desktop/Django/conbrio11/app/forms.py
from django.forms import ModelForm
from .models import Plan

class PlanForm(ModelForm):
    class Meta:
        model=Plan
        fields=['title','meeting_place','moving_method','second_place','third_place',]

Desktop/Django/conbrio11/app/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth.models import User
from .models import Category,Plan
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from .forms import PlanForm
from django.contrib import messages

# Create your views here.

class Index(ListView):
    model=Plan
    template_name='app/index.html'
# def index(request):
#     plans=Plan.objects.all().order_by('-created_at')
#     return render(request,'app/index.html',{'plans':plans})

def users_detail(request,pk):
    user=get_object_or_404(User,pk=pk)
    photos=user.plan_set.all().order_by('-created_at')
    return render(request,'app/users_detail.html',{'user':user,'photos':photos})

def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            new_user=form.save()
            input_username=form.cleaned_data['username']
            input_password=form.cleaned_data['password1']
            # input_email=form.cleaned_data['email']
            new_user=authenticate(username=input_username,password=input_password)
            if new_user is not None:
                login(request,new_user)
                return redirect('mainapp:users_detail',pk=new_user.pk)
    else:
        form=UserCreationForm()
    return render(request,'app/signup.html', {'form':form})

@login_required
def plans_new(request):
    if request.method=='POST':
        form=PlanForm(request.POST,request.FILES)
        if form.is_valid():
            plan=form.save(commit=False)
            plan.user=request.user
            plan.save()
            messages.success(request,'投稿が完了しました')
        return redirect('app/users_detail',pk=request.user.pk)
    else:
        form=PlanForm()
    return render(request,'mainapp/plans_new.html' , {'form':form})

def plans_category(request,category):
    category=Category.objects.get(title=category)
    plans=Plan.objects.filter(category=category),order_by('-created_at')
    return render(request,'app/index.html',{'category':category,'plans':plans})

Desktop/Django/conbrio11/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja-JP">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Great+Vibes|Kaushan+Script|Permanent+Marker&display=swap" rel="stylesheet">

<title>Title</title>
</head>
<body>

  <div class="container-header">
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4">
          <a href="{%url 'mainapp:index'%}"><h1>Conbrio</h1></a>
        </div>

        <div class="col-sm-1 col-md-2 col-lg-2" ></div>

    <div class="col-sm-6 col-md-4 col-lg-4" style="padding-top: 10px;" >
       <i class="fab fa-twitter"></i>
       <i class="fab fa-facebook-square"></i>
       <i class="fab fa-instagram"></i>
      </div>

      {% if request.user.is_authenticated %}  
        <h5 class="nav-item dropdown" style="margin-top: -20px; color:rgb(167, 133, 110);">
            <a  href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle" style="font-size: 50px; padding-left: 50px;"></i>
              </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="color:rgb(167, 133, 110);">
              <a class="dropdown-item" href="{% url 'mainapp:plans_new' %}">??</a>
              <a class="dropdown-item" href="{% url 'mainapp:logout' %}">Logout</a>
            </div>
          </h5>
      {% else %}
        <h5 class="nav-item">
            <a href="{%url 'mainapp:login'%}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 70px;">login</a>
            <a href="{%url 'mainapp:signup'%}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 20px;">signup</a>
       </h5>
      {% endif %}
        </div>
    </div>
  </div>
</div>
</div>

{% block content %}
{% endblock %}


<a href="/" style="text-align: center;"><h6>Conbrio</h6></a>




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/css" src="{%static 'js/style.js'%}"></script>

</body>
</html>

Desktop/Django/conbrio11/app/templates/app/login.html
{% extends "app/base.html" %}
{% block content %}

<form class="form-signin" method="POST">{% csrf_token %}
    {%if form.errors%}
    <p>ユーザー名かパスワードが間違っています</p>
    {%endif%}
    <h2>ログイン</h2>
    <label>ユーザー名</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>

{% endblock %}

Desktop/Django/conbrio11/app/templates/app/plans_detail.html
{% extends "app/base.html" %}
{% block content %}
<h5>{{user.username}}</h5>
<div class="plan_container">
    {%for plan in plans%}
    <div class="plan">
        <a href="">
            <img src="{{plan.image.url}}" class="plan-img">
        </a>
        <div class="plan-info">
            <a href=""class="category">{{plan.category}}</a>
            <a href="{%url 'app/users_detail' plan.user.id%}">{{plan.user}}</a>
        </div>
    </div>
    {%endfor%}
</div>  


{% if category %}
<h5>{{category.title}}</h5>
{%endif%}
  
<div class="container">
    <div class="row">
        {% for product in object_list %}
         {%csrf_token%}
        <div class="col-4">
            <img src="media/{{ product.mainimage }}" style="width: 300px; height: auto;">
            <p>{{ product.name }}</p>
        </div>
        {% endfor %}
    </div>
</div>




<div class="photo_container">
    {%for plan in plans%}
    <a src="{%url 'mainapp:plans_new' plan.id%}">
    <img src=media/{{ product.mainimage }}></a>
</div>
<div class="photo-info">
        <a href="{% url 'app:photos_category' category=photo.category %}"
        class="category">{{ plan.category }}</a> 
        <a href="{% url 'mainapp:users_detail' plan.user.id %}">
            @{{ photo.user }}</a>
    
    </div>
    {% endfor %}
</div>
  



{%include 'app/plans_list.html'%}

{% endblock %}

Desktop/Django/conbrio11/app/templates/app/plans_new.html
{% extends "app/base.html" %}
{% block content %}

<form action="{% url 'mainapp:plans_new' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}

<table>
    <tr>
        <th>タイトル</th>
        <td>{{form.title}}</td>
    </tr>
    <tr>
        <th>集合場所</th>
        <td>{{form.meeting_place}}</td>
    </tr>
    <tr>
        <th>移動手段</th>
        <td>{{form.moving_method}}</td>
    </tr>
    <tr>
        <th>第二ポイント</th>
        <td>{{form.second_place}}</td>
    </tr>
    <tr>
        <th>第三ポイント</th>
        <td>{{form.third_place}}</td>
    </tr>
    <!-- <tr>
        <th>投稿日時</th>
        <td>{{form.created_at}}</td>
    </tr> -->
    </table>
<button type="submit" class="btn">保存</button>
</form>
  
{% endblock %}

Desktop/Django/conbrio11/app/templates/app/signup.html
{% extends "app/base.html" %}
{% block content %}

<h2>ユーザー登録</h2>

<form method="POST" action="{%url 'mainapp:signup'%}">
    {% csrf_token %}
<label>ユーザー名</label>
{{form.username}}
{{form.username.errors}}
<br>
<label>パスワード</label>
{{form.password1}}
{{form.password1.errors}}
<br>
<label>パスワード（確認）</label>
{{form.password2}}
{{form.password2.errors}}
<br>
<!-- <label>メールアドレス</label>
{{form.email}}
{{form.email.errors}}
<br> -->
<input type="submit" value="登録する">
</form>

<p><a href="{%url 'mainapp:login'%}"></a></p>


{% endblock %}

Desktop/Django/conbrio11/app/templates/app/users_detail.html
{% extends "app/base.html" %}
{% block content %}

<h6 class="plan-name">@{{user.username}}</h6>

{% if category %}
<h5>{{category.title}}</h5>
{%endif%}
  
<div class="container">
    <div class="row">
        {% for product in object_list %}
         {%csrf_token%}
        <div class="col-4">
            <img src="media/{{ product.mainimage }}" style="width: 300px; height: auto;">
            <p>{{ product.name }}</p>
        </div>
        {% endfor %}
    </div>
</div>

{%endblock%}