Desktop/Django/conbrio3/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='app'

urlpatterns = [
    path('',views.index,name='index'),
    path('plans/',views.plans,name='plans'),
    path('categol/<int:pk>/',views.plan_list,name='plan_list'),
    path('plans/new/',views.plans_new,name='plans_new'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='app/login.html'),
    name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),

]

Desktop/Django/conbrio3/conbrio3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('app.urls'))
]



urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desktop/Django/conbrio3/app/models.py
from django.db import models
from users.models import User

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='photos',default=1)
    primaryCategory=models.BooleanField(default=False)
    slug=models.SlugField()

    def __str__(self):
        return self.slug

class Plan(models.Model):
    title=models.CharField(max_length=200)
    place=models.CharField(max_length=200)
    moving_method = models.CharField(max_length=200)
    second_place = models.CharField(max_length=200)
    third_place = models.CharField(max_length=200)
    totaltime=models.IntegerField()
    created_at=models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to='photos')
    categories=models.ForeignKey('Category',on_delete=models.PROTECT)
    name=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title   

Desktop/Django/conbrio3/users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser 
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):

    """カスタムユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, sirname, email, password, **extra_fields): # email を必須にする
        if not sirname:
            raise ValueError('メールアドレスが入力されていません。')
        if not email:
            raise ValueError('メールアドレスが入力されていません。')

        email = self.normalize_email(email)
        sirname = self.models.sirname(sirname)
        user = self.model(sirname=sirname,email=email,**extra_fields)
        user.set_password(password)
        user.save(self.db)
        
        return user

    def create_user(self,sirname ,email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(sirname, email, password,**extra_fields)
    
    def create_superuser(self,sirname ,email, password,**extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(sirname, email, password, **extra_fields)


# User モデルより上に記載する

class User(AbstractBaseUser, PermissionsMixin): 
    """カスタムユーザーモデル"""
    sirname = models.CharField(max_length=100)
    email = models.EmailField("メールアドレス", unique=True)
    name = models.CharField(max_length=30, blank=True,)
    is_staff = models.BooleanField("is_staff", default=False)
    is_active = models.BooleanField("is_active", default=True)
    date_joined = models.DateTimeField("date_joined",default=timezone.now)

    objects = UserManager()


    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ['sirname']


    class Meta:
        verbose_name = "user" 
        verbose_name_plural = "users"

Desktop/Django/conbrio3/app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=get_user_model()
        fields=('email','sirname',)


from django.forms import ModelForm
from .models import Plan

class PlanForm(ModelForm):
    class Meta:
        model=Plan
        fields=['title','image','place','moving_method','second_place','third_place','totaltime','name']

Desktop/Django/conbrio3/app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from .forms import CustomUserCreationForm,PlanForm
from .models import Plan,Category
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'app/index.html')



def plans(request):
    plans=Plan.objects.all().order_by('-created_at')
    return render(request,'app/plans.html',{'plans':plans})


def plan_list(request,pk):
    categol=get_object_or_404(Category,pk=pk)
    planning=categol.plan_set.all().order_by('-creates_at')

    return render(request,'app/plan_list.html',{'planning':planning,'categol':categol})



def signup(request):
    if request.method=='POST':
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user=form.save()
            input_email=form.cleaned_data['name']
            input_email=form.cleaned_data['email']
            input_password=form.cleaned_data['password1']
            new_user=authenticate(name=input_name,email=input_email,password=input_password)
            if new_user is not None:
                login(request,new_user)
                return redirect('app:index')
            
    else:
        form=CustomUserCreationForm()
    return render(request,'app/signup.html',{'form':form})


@login_required
def plans_new(request):
    if request.method=="POST":
        form=PlanForm(request.POST,request.FILES)
        if form.is_valid():
            plan=form.save(commit=False)
            plan.name=request.user
            plan.save()
        return redirect('app:plan_list',pk=request.user.pk)
    else:
        form=PlanForm()
    return render(request,'app/plans_new.html',{'form':form})

Desktop/Django/conbrio3/users/views.py
from django.shortcuts import render

# Create your views here.

Desktop/Django/conbrio3/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja-JP">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Great+Vibes|Kaushan+Script|Permanent+Marker&display=swap" rel="stylesheet">

<title>Title</title>
</head>
<body>

  <div class="container-header">
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4">
          <a href="{%url 'app:index'%}"><h1>Conbrio</h1></a>
        </div>

        <div class="col-sm-1 col-md-2 col-lg-2" ></div>

    <div class="col-sm-6 col-md-4 col-lg-4" style="padding-top: 10px;" >
       <i class="fab fa-twitter"></i>
       <i class="fab fa-facebook-square"></i>
       <i class="fab fa-instagram"></i>
      </div>

      {% if request.user.is_authenticated %}  
        <h5 class="nav-item dropdown" style="margin-top: -20px; color:rgb(167, 133, 110);">
            <a  href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle" style="font-size: 50px; padding-left: 50px;"></i>
              </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="color:rgb(167, 133, 110);">
              <a class="dropdown-item" href="{%url 'app:plans_new'%}">投稿</a>
              <a class="dropdown-item" href="{%url 'app:logout' %}">Logout</a>
            </div>
          </h5>
      {% else %}
        <h5 class="nav-item">
            <a href="{%url 'app:login'%}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 70px;">login</a>
            <a href="{%url 'app:signup'%}" style="color: rgb(167, 133, 110); font-size: 20px; padding-left: 20px;">signup</a>
       </h5>
      {% endif %}
        </div>
    </div>
  </div>
</div>
</div>

{% block content %}
{% endblock %}


<a href="/" style="text-align: center;"><h6>Conbrio</h6></a>




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/css" src="{%static 'js/style.js'%}"></script>

</body>
</html>

Desktop/Django/conbrio3/app/templates/app/login.html
{% extends "app/base.html" %}
{% block content %}
  
<div class="container-login">
    <div class="row">
            <div class="col-sm-6 col-md-12 col-lg-12">
        <form class="form-sigin" method="POST">{% csrf_token %}


    <!-- <h2>login</h2>
    <label>メールアドレス</label>
    <input name="username">
    <br>
    <label>password</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン"> -->

    <!-- <h6 style="font-size:20px;">メールアドレスとパスワードを入力してください。</h6>
    <label style="color:rgb(167, 133, 110);">mailaddress:</label>
    <input name="username">
    <br>
    <label style="color:rgb(167, 133, 110);">password   :  </label>
    <input type="password" name="password">
    <br> -->

    <h6>こちらからログインお願いします。</h6>



    <div class="container-login">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-lg-4"></div>
                <div class="col-sm-6 col-md-4 col-lg-4">
        <p style="color:rgb(167, 133, 110);"> {{form}}</p>
    <input type="submit" style="color: white; background-color:rgb(167, 133, 110);" value="ログイン">
</div>
</div>
</div>
</form>

{% endblock %}

Desktop/Django/conbrio3/app/templates/app/signup.html
{% extends "app/base.html" %}
{% block content %}

<div class="container-login">
    <div class="row">
            <div class="col-sm-6 col-md-12 col-lg-12">

<h3>ユーザー登録</h3>
<form method="POST" action="{%url 'app:signup' %}" style=" color: rgb(167, 133, 110); ">{% csrf_token %}
    <label>name</label>
    {{form.sirname}}
    {{form.sirname.errors}}
    <br>
    <label>meiladdress</label>
    {{form.email}}
    {{form.email.errors}}
    <br>
    <label>password</label>
    {{form.password1}}
    {{form.password1.errors}}
    <br>
    <label>password(確認用)</label>
    {{form.password2}}
    {{form.password2.errors}}
    <br>



    
    <input style=" color: rgb(167, 133, 110);" type="submit" value="登録する">
    

</form>
  
{% endblock %}